apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: apps
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: user-service
                topologyKey: kubernetes.io/hostname
