apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: item-service
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: app.localtest.me
      http:
        paths:
          - path: /api/items(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: item-service
                port:
                  number: 9898
