apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps-default-deny.yaml
  - infra-default-deny.yaml
  - observability-default-deny.yaml
  - allow-dns-egress-apps.yaml
  - allow-dns-egress-infra.yaml
  - allow-dns-egress-observability.yaml
  - allow-ingress-controller-to-apps.yaml
  - allow-apps-to-postgres.yaml
  - allow-observability-to-postgres.yaml
