apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-db-secret
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: sample-store
  target:
    name: db-credentials
  data:
    - secretKey: username
      remoteRef:
        key: prod/db/app
        property: username
    - secretKey: password
      remoteRef:
        key: prod/db/app
        property: password
