apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service
  namespace: apps
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  namespaceSelector:
    matchNames:
      - apps
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
