apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps-namespace-label.yaml
  - sleep-deployment.yaml
  - peer-authentication.yaml
  - user-service-virtualservice.yaml
  - user-service-destinationrule.yaml
