server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    global:
      domain: argocd.localtest.me
    hosts:
      - argocd.localtest.me
  extraArgs:
    - --insecure

configs:
  params:
    server.insecure: true
