apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - postgres-exporter-secret.yaml
  - postgres-exporter-deployment.yaml
  - postgres-exporter-service.yaml
  - postgres-exporter-servicemonitor.yaml
