apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/part-of: kind-study
spec:
  selector:
    app.kubernetes.io/name: postgres-exporter
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
