apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-exporter
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: metrics
      interval: 15s
