apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind-study-apps
  namespace: gitops
spec:
  project: kind-study
  source:
    repoURL: https://github.com/taigamiura/kind-study.git
    targetRevision: main
    path: manifests/overlays/local/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
