apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops
resources:
  - app-project.yaml
  - infra-application.yaml
  - apps-application.yaml
  - observability-application.yaml
