apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: apps
spec:
  template:
    spec:
      containers:
        - name: user-service
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
